/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "o2xfs-memory-impl-bin.h"
#include <cassert>

int main() {
    o2xfs_memory_impl_bin::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
